title: roymatsunaga.com
email: your-email@example.com
baseurl: ""
domain: "https://roymatsunaga.com"
permalink: pretty
github_username: roymatsunaga
exclude: [ _styles, node_modules, .git, .gitignore, package.json, README.md, .sass-cache ]